### ISSUE TITLE
Password retrieval feature needed

### ISSUE THREAD

**Issue by lozanaross** [Kompakkt/Kompakkt#7]
### What

Users need to be able to retrieve passwords (or usernames) via email.

### Why

Because at the moment this is not possible, but it's an essential feature. Also helpful when errors during sign up happen, see issue #6 

### Mockup
Step 1:
![Screenshot 2022-06-15 at 17 38 31](https://user-images.githubusercontent.com/25489750/173869077-672f73e1-e1da-4557-a520-575fc8a33bba.png)

Step 2: 
![Screenshot 2022-06-15 at 17 33 38](https://user-images.githubusercontent.com/25489750/173868996-3ac877f7-3de4-443d-9e85-8e56e83fc1d8.png)

The email sent to the user should then contain the username associated with the account and a link to reset password.

Step 3:
![Screenshot 2022-06-15 at 17 40 30](https://user-images.githubusercontent.com/25489750/173868947-a108691b-37c1-49f9-a1eb-20275f90c54b.png)

**Comment by HeyItsBATMAN** [comment]
Should be solved by https://github.com/Kompakkt/Repo/pull/4

**Comment by Grizzly127** [comment]
Hello, I'm currently working on a new design for the login. What was the issue with having a button for 'Forgot password' and 'forgot username' ? Can we only use one button for it? @HeyItsBATMAN
