### ISSUE TITLE
Improve sizes of container and viewer inside the upload wizard to avoid cut-off buttons and extra scrolling

### ISSUE THREAD

**Issue by lozanaross** [Kompakkt/Kompakkt#8]
### What
Currently the upload wizard has dimensions that produce unnecessary scrollbars and the next buttons are cut off - it's not an optimal user experience and screen space is wasted. There are three parameters to address here, the height of the container; the height of the viewer iframe; the size of the "Edit Object" dialog title, which is taking up a lot of space and making optimization harder.

### Why
We should fix this in order to avoid situations like this:

![Screenshot 2022-06-15 at 18 14 20](https://user-images.githubusercontent.com/25489750/174331190-a6990b9e-c2e6-49b1-b619-d8ad643b2d45.png)

And this on a smaller screen:
![Screenshot 2022-06-15 at 18 22 58](https://user-images.githubusercontent.com/25489750/174331216-98171d85-4340-47d8-8f7a-01e6ff6fe02c.png)

Ideally, the changes are coordinated with the TIB version of Kompakkt so the two instances can be in line. Below I share some values that produce good functioning overlays across both the semantic version and the regular Kompakkt.

### Mockup

1) - [ ] Fix the height of the container, like so:

![Screenshot 2022-06-15 at 18 23 39](https://user-images.githubusercontent.com/25489750/174331878-e121edbf-d2aa-4b22-92b6-6f8e0773845d.png)

2) - [ ] Fix the height of the viewer iFrame like so: 

![Screenshot 2022-06-15 at 18 27 39](https://user-images.githubusercontent.com/25489750/174331909-ee20cf64-d893-4f8f-8f6f-e6ae5365d05d.png)

3) - [ ] Fix the size & styling of the dialog title, like so:

![Screenshot 2022-06-15 at 18 30 19](https://user-images.githubusercontent.com/25489750/174331932-2f258d4c-5814-408e-9572-bc16e8102241.png)

The result should be like this:

![Screenshot 2022-06-15 at 18 32 13](https://user-images.githubusercontent.com/25489750/174332098-52540ec2-d836-45dc-bb3a-a373686076ce.png)

**Comment by HeyItsBATMAN** [comment]
Should be closed by https://github.com/Kompakkt/Repo/pull/5
